apiVersion: v1
kind: Service
metadata:
  name: gestionemploidutemps
  namespace: preprod
spec:
  selector:
    app: gestionemploidutemps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: NodePort
  